ALTER TABLE `roles`
ADD `permission` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT null AFTER `status`;

CREATE TABLE `roles_location_department` (
  `role_id` bigint UNSIGNED NOT NULL,
  `location_id` bigint(20) UNSIGNED DEFAULT NULL,
  `department_id` bigint(20) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `roles_location_department`
  ADD CONSTRAINT `fk_roles` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_roles_departemnt` FOREIGN KEY (`department_id`) REFERENCES `organization_departments` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_roles_location` FOREIGN KEY (`location_id`) REFERENCES `organization_locations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE `permissions`
   ADD `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '1:read,2:Write,3:Delete' AFTER `name`;


--For Modules Permissions
INSERT INTO `permissions` 
(`name`,`status`,`type`)
VALUES 
(`hrms_dashboard_view`,1,2),
(`basic_details_view`,1,2),
(`basic_details_edit`,2,2),
(`basic_details_download`,2,2),
(`bank_details_view`,1,2),
(`bank_details_edit`,2,2),
(`bank_details_download`,2,2),
(`compliance_details_view`,1,2),
(`compliance_details_edit`,2,2),
(`compliance_details_download`,2,2),
(`component_and_prerequsite_view`,1,2),
(`component_and_prerequsite_edit`,2,2),
(`component_and_prerequsite_download`,2,2),
(`hrms_attendance_view`,1,2),
(`hrms_attendance_edit`,2,2),
(`overview_view`,1,2),
(`attendance_and_leaves_view`,1,2),
(`salary_revision_view`,1,2),
(`salary_on_hold_view`,1,2),
(`salary_on_hold_edit`,2,2),
(`preview_and_run_payroll_view`,1,2),
(`pay_register_view`,1,2),
(`pay_register_download`,2,2),
(`payout_view`,1,2),
(`setuppayroll_payroll_setting_view`,1,2),
(`setuppayroll_payroll_setting_edit`,2,2),
(`assign_structure_view`,1,2),
(`assign_structure_edit`,2,2),
(`create_structure_view`,1,2),
(`create_structure_edit`,2,2),
(`tax_scheme_view`,1,2),
(`tax_scheme_edit`,2,2),
(`section80c_view`,1,2),
(`section80c_edit`,2,2),
(`house_rent_view`,1,2),
(`house_rent_edit`,2,2),
(`LTA_view`,1,2),
(`LTA_edit`,2,2),
(`loans_view`,1,2),
(`loans_edit`,2,2),
(`savings_banks_view`,1,2),
(`savings_banks_edit`,2,2),
(`other_than_savings_view`,1,2),
(`other_than_savings_edit`,2,2),
(`one_house_property_view`,1,2),
(`one_house_property_edit`,2,2),
(`pension_family_view`,1,2),
(`pension_family_edit`,2,2),
(`income_from_previous_employer_view`,1,2),
(`income_from_previous_employer_edit`,2,2),
(`advanced_setting_payroll_setting_view`,1,2),
(`advanced_setting_payroll_setting_edit`,2,2),
(`PF_and_ESI_view`,1,2),
(`PF_and_ESI_edit`,2,2),
(`PT_setting_view`,1,2),
(`PT_setting_edit`,2,2),
(`declaration_setting_view`,1,2),
(`declaration_setting_edit`,2,2),
(`leave_view`,1,2),
(`leave_edit`,2,2),
(`leave_create`,2,2),
(`attendance_requests_view`,1,2),
(`attendance_requests_edit`,2,2),
(`attendance_requests_create`,2,2),
(`leave_types_view`,1,2),
(`leave_types_edit`,2,2),
(`leave_types_create`,2,2),
(`leave_types_delete`,3,2),
(`holidays_view`,1,2),
(`holidays_edit`,2,2),
(`holidays_create`,2,2),
(`holidays_delete`,3,2),
(`attendance_settings_view`,1,2),
(`attendance_settings_edit`,2,2),
(`loans_delete`,3,2)
(`run_payroll_view`,1,2),
(`run_payroll_edit`,2,2),
(`hrms_employee_myprofile_view`,1,2),
(`hrms_employee_myprofile_edit`,2,2),
(`hrms_employee_attendance_view`,1,2),
(`hrms_employee_attendance_edit`,2,2),
(`hrms_employee_overview_view`,1,2),
(`hrms_employee_section80c_view`,1,2),
(`hrms_employee_section80c_edit`,2,2),
(`hrms_employee_section80c_delete`,3,2),
(`hrms_employee_house_rent_view`,1,2),
(`hrms_employee_house_rent_edit`,2,2),
(`hrms_employee_house_rent_delete`,3,2),
(`hrms_employee_LTA_view`,1,2),
(`hrms_employee_LTA_edit`,2,2),
(`hrms_employee_LTA_delete`,3,2),
(`hrms_employee_loans_view`,1,2),
(`hrms_employee_loans_edit`,2,2),
(`hrms_employee_loans_delete`,3,2),
(`hrms_employee_saving_bank_interest_view`,1,2),
(`hrms_employee_saving_bank_interest_edit`,2,2),
(`hrms_employee_saving_bank_interest_delete`,3,2),
(`hrms_employee_other_than_saving_acc_view`,1,2),
(`hrms_employee_other_than_saving_acc_edit`,2,2),
(`hrms_employee_other_than_saving_acc_delete`,3,2),
(`hrms_employee_one_house_property_view`,1,2),
(`hrms_employee_one_house_property_edit`,2,2),
(`hrms_employee_one_house_property_delete`,3,2),
(`hrms_employee_pension_family_view`,1,2),
(`hrms_employee_pension_family_edit`,2,2),
(`hrms_employee_pension_family_delete`,3,2),
(`hrms_employee_income_from_pre_employer_view`,1,2),
(`hrms_employee_income_from_pre_employer_edit`,2,2),
(`hrms_employee_income_from_pre_employer_delete`,3,2),
(`hrms_employee_payslip_view`,1,2),
(`hrms_employee_payslip_download`,2,2),
(`hrms_employee_leave_view`,1,2),
(`hrms_employee_leave_edit`,2,2),
(`hrms_employee_leave_delete`,3,2)
;